# workflow used to deploy
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      functions:
        description: 'Write functions name separated by comma or "all" to deploy all functions'
        required: true
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Install npm packages
        run: |
          cd functions
          npm install

      - if: ${{ github.event.inputs.functions != 'all' }}
        name: Deploy specific function to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:${{ github.event.inputs.functions }}
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: airpals-aa318

      - if: ${{ github.event.inputs.functions == 'all' }}
        name: Deploy all functions to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: airpals-aa318
